#!/usr/bin/env python3
"""
Generate project-local cached-power tables for float decimal parsing.

This script exists so checked-in tables can be regenerated from a simple,
auditable mathematical procedure instead of being copied from an external
implementation.
"""

from __future__ import annotations


def emit() -> str:
    max_u64_q = 27
    max_u128_q = 55
    max_scaled_u128_q = 350
    max_inv_u128_q = 350
    u64_values = [5**q for q in range(max_u64_q + 1)]
    u128_values = [5**q for q in range(max_u128_q + 1)]
    scaled_u128_values = []
    for q in range(max_scaled_u128_q + 1):
        value = 5**q
        bit_length = value.bit_length()
        shift = bit_length - 127 if bit_length > 127 else 0
        scaled = value >> shift
        scaled_u128_values.append((scaled, shift))
    inv_u128_values = []
    for q in range(max_inv_u128_q + 1):
        denom = 5**q
        shift = denom.bit_length() + 127
        recip = ((1 << shift) - 1) // denom
        inv_u128_values.append((recip, shift))
    lines = [
        "/*",
        " * Generated by scripts/generate_float_decimal_tables.py.",
        " *",
        " * This file contains exact integer powers of 5 used by the current",
        " * staged Eisel-Lemire fast path, plus generated reciprocal caches for",
        " * wider negative-exponent candidate assembly. The values are generated",
        " * locally from 5**q and are not copied from any external parser",
        " * implementation.",
        " */",
        "",
        "#ifndef PROVEN_FLOAT_DECIMAL_TABLES_H",
        "#define PROVEN_FLOAT_DECIMAL_TABLES_H",
        "",
        '#include "proven/types.h"',
        "",
        "#define PROVEN_FLOAT_CACHED_POW5_U64_MAX_Q 27u",
        "#define PROVEN_FLOAT_CACHED_POW5_U128_MAX_Q 55u",
        "#define PROVEN_FLOAT_CACHED_POW5_SCALED_U128_MAX_Q 350u",
        "#define PROVEN_FLOAT_CACHED_POW5_INV_U128_MAX_Q 350u",
        "",
        "typedef struct proven_float_cached_pow5_u128_entry_t {",
        "    proven_u64 lo;",
        "    proven_u64 hi;",
        "} proven_float_cached_pow5_u128_entry_t;",
        "",
        "typedef struct proven_float_cached_pow5_inv_u128_entry_t {",
        "    proven_u64 lo;",
        "    proven_u64 hi;",
        "    proven_u16 shift;",
        "} proven_float_cached_pow5_inv_u128_entry_t;",
        "",
        "typedef struct proven_float_cached_pow5_scaled_u128_entry_t {",
        "    proven_u64 lo;",
        "    proven_u64 hi;",
        "    proven_u16 shift;",
        "} proven_float_cached_pow5_scaled_u128_entry_t;",
        "",
        "static const proven_u64 proven_float_cached_pow5_u64[] = {",
    ]
    for value in u64_values:
        lines.append(f"    {value}ull,")
    lines.extend(
        [
            "};",
            "",
            "static const proven_float_cached_pow5_u128_entry_t proven_float_cached_pow5_u128[] = {",
        ]
    )
    for value in u128_values:
        lo = value & ((1 << 64) - 1)
        hi = value >> 64
        lines.append(f"    {{ .lo = 0x{lo:016x}ull, .hi = 0x{hi:016x}ull }},")
    lines.extend(
        [
            "};",
            "",
            "static const proven_float_cached_pow5_scaled_u128_entry_t proven_float_cached_pow5_scaled_u128[] = {",
        ]
    )
    for scaled, shift in scaled_u128_values:
        lo = scaled & ((1 << 64) - 1)
        hi = scaled >> 64
        lines.append(f"    {{ .lo = 0x{lo:016x}ull, .hi = 0x{hi:016x}ull, .shift = {shift}u }},")
    lines.extend(
        [
            "};",
            "",
            "static const proven_float_cached_pow5_inv_u128_entry_t proven_float_cached_pow5_inv_u128[] = {",
        ]
    )
    for recip, shift in inv_u128_values:
        lo = recip & ((1 << 64) - 1)
        hi = recip >> 64
        lines.append(f"    {{ .lo = 0x{lo:016x}ull, .hi = 0x{hi:016x}ull, .shift = {shift}u }},")
    lines.extend(
        [
            "};",
            "",
            "#endif /* PROVEN_FLOAT_DECIMAL_TABLES_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    print(emit(), end="")


if __name__ == "__main__":
    main()
