#!/usr/bin/env python3
"""
Generate project-local cached-power tables for float decimal parsing.

This script exists so checked-in tables can be regenerated from a simple,
auditable mathematical procedure instead of being copied from an external
implementation.
"""

from __future__ import annotations

import math


def grisu_cached_power(k: int) -> tuple[int, int]:
    """Return (f, e) with 10**k ~= f * 2**e, 2**63 <= f < 2**64, round to nearest."""
    e = math.floor(k * math.log2(10)) - 63
    if k >= 0:
        num, den = (10 ** k), 1
    else:
        num, den = 1, (10 ** (-k))
    if e <= 0:
        num <<= (-e)
    else:
        den <<= e
    f = (2 * num + den) // (2 * den)  # round to nearest
    if f >= (1 << 64):
        f >>= 1
        e += 1
    assert (1 << 63) <= f < (1 << 64)
    return f, e


def emit() -> str:
    # Grisu3 cached powers of ten: decimal exponents -348..340 in steps of 8.
    grisu_min_decimal_exp = -348
    grisu_max_decimal_exp = 340
    grisu_distance = 8
    grisu_powers = [
        (k, *grisu_cached_power(k))
        for k in range(grisu_min_decimal_exp, grisu_max_decimal_exp + 1, grisu_distance)
    ]

    max_u64_q = 27
    max_u128_q = 55
    max_scaled_u128_q = 350
    max_inv_u128_q = 350
    u64_values = [5**q for q in range(max_u64_q + 1)]
    u128_values = [5**q for q in range(max_u128_q + 1)]
    scaled_u128_values = []
    for q in range(max_scaled_u128_q + 1):
        value = 5**q
        bit_length = value.bit_length()
        shift = bit_length - 127 if bit_length > 127 else 0
        scaled = value >> shift
        scaled_u128_values.append((scaled, shift))
    inv_u128_values = []
    for q in range(max_inv_u128_q + 1):
        denom = 5**q
        shift = denom.bit_length() + 127
        recip = ((1 << shift) - 1) // denom
        inv_u128_values.append((recip, shift))
    lines = [
        "/*",
        " * Generated by scripts/generate_float_decimal_tables.py.",
        " *",
        " * This file contains exact integer powers of 5 used by the current",
        " * staged Eisel-Lemire fast path, plus generated reciprocal caches for",
        " * wider negative-exponent candidate assembly. The values are generated",
        " * locally from 5**q and are not copied from any external parser",
        " * implementation.",
        " */",
        "",
        "#ifndef PROVEN_FLOAT_DECIMAL_TABLES_H",
        "#define PROVEN_FLOAT_DECIMAL_TABLES_H",
        "",
        '#include "proven/types.h"',
        "",
        "#define PROVEN_FLOAT_CACHED_POW5_U64_MAX_Q 27u",
        "#define PROVEN_FLOAT_CACHED_POW5_U128_MAX_Q 55u",
        "#define PROVEN_FLOAT_CACHED_POW5_SCALED_U128_MAX_Q 350u",
        "#define PROVEN_FLOAT_CACHED_POW5_INV_U128_MAX_Q 350u",
        "",
        "typedef struct proven_float_cached_pow5_u128_entry_t {",
        "    proven_u64 lo;",
        "    proven_u64 hi;",
        "} proven_float_cached_pow5_u128_entry_t;",
        "",
        "typedef struct proven_float_cached_pow5_inv_u128_entry_t {",
        "    proven_u64 lo;",
        "    proven_u64 hi;",
        "    proven_u16 shift;",
        "} proven_float_cached_pow5_inv_u128_entry_t;",
        "",
        "typedef struct proven_float_cached_pow5_scaled_u128_entry_t {",
        "    proven_u64 lo;",
        "    proven_u64 hi;",
        "    proven_u16 shift;",
        "} proven_float_cached_pow5_scaled_u128_entry_t;",
        "",
        "static const proven_u64 proven_float_cached_pow5_u64[] = {",
    ]
    for value in u64_values:
        lines.append(f"    {value}ull,")
    lines.extend(
        [
            "};",
            "",
            "static const proven_float_cached_pow5_u128_entry_t proven_float_cached_pow5_u128[] = {",
        ]
    )
    for value in u128_values:
        lo = value & ((1 << 64) - 1)
        hi = value >> 64
        lines.append(f"    {{ .lo = 0x{lo:016x}ull, .hi = 0x{hi:016x}ull }},")
    lines.extend(
        [
            "};",
            "",
            "static const proven_float_cached_pow5_scaled_u128_entry_t proven_float_cached_pow5_scaled_u128[] = {",
        ]
    )
    for scaled, shift in scaled_u128_values:
        lo = scaled & ((1 << 64) - 1)
        hi = scaled >> 64
        lines.append(f"    {{ .lo = 0x{lo:016x}ull, .hi = 0x{hi:016x}ull, .shift = {shift}u }},")
    lines.extend(
        [
            "};",
            "",
            "static const proven_float_cached_pow5_inv_u128_entry_t proven_float_cached_pow5_inv_u128[] = {",
        ]
    )
    for recip, shift in inv_u128_values:
        lo = recip & ((1 << 64) - 1)
        hi = recip >> 64
        lines.append(f"    {{ .lo = 0x{lo:016x}ull, .hi = 0x{hi:016x}ull, .shift = {shift}u }},")
    lines.extend(
        [
            "};",
            "",
        ]
    )

    lines.extend(
        [
            f"#define PROVEN_FLOAT_GRISU_MIN_DECIMAL_EXP {grisu_min_decimal_exp}",
            f"#define PROVEN_FLOAT_GRISU_DECIMAL_DISTANCE {grisu_distance}u",
            f"#define PROVEN_FLOAT_GRISU_POWER_COUNT {len(grisu_powers)}u",
            "",
            "typedef struct proven_float_grisu_power_t {",
            "    proven_u64 f;",
            "    proven_i16 e;",
            "    proven_i16 k;",
            "} proven_float_grisu_power_t;",
            "",
            "static const proven_float_grisu_power_t proven_float_grisu_powers[] = {",
        ]
    )
    for k, f, e in grisu_powers:
        lines.append(f"    {{ .f = 0x{f:016x}ull, .e = {e}, .k = {k} }},")
    lines.extend(
        [
            "};",
            "",
            "#endif /* PROVEN_FLOAT_DECIMAL_TABLES_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    print(emit(), end="")


if __name__ == "__main__":
    main()
